name: Integracion Continua

on:
  push:
    branches:
      - main

jobs:
  verificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar confirmacion
        run: echo "La automatizacion se ha ejecutado correctamente"

      - name: Listar archivos
        run: ls -la